export const GameConfig = Object.freeze({
  PlayerRadius: 0.28,
  PlayerColliderHeight: 1.68,
  MaxStepHeight: 0.32,
  CollisionSkin: 0.008,
  WalkSpeed: 4.1,
  SprintSpeed: 6.6,
  JumpSpeed: 5.4,
  Gravity: 14.5,
  StaminaDrain: 23,
  StaminaRegen: 17,
  StaminaRegenDelay: 0.8,
  CameraMin: 2.0,
  CameraMax: 5.5,
  CameraDefault: 3.4,
  CameraHeight: 1.55,
  CameraShoulder: 0.5,
  CameraTargetDamping: 38,
  CameraBoomDamping: 20,
  CameraPositionDamping: 30,
  CameraCollisionPadding: 0.16,
  PoliceResponseDelay: 10,
  LootCount: 5,
  RequiredLoot: 3,
  LootValue: 50000,
  BreachCooldown: 0.16
});
